### ISSUE TITLE
Getting access to pet menu

### ISSUE THREAD

**Issue by incoregod** [FelisDevelopment/fd-pets-support#1]
Hello, i got today the script like a hour ago, i can use the command ["command"] = "spawnpet", 
and i can spawn all the pets in the cfg file. 

issue: i still cant get the menu open.
those general default binds not working, already tryed with some difrent keys.
 ["actionWithoutSelection"] = {
 ["defaultBind"] = "",
 ["text"] = "Open basic pet menu"

tnhks

**Comment by incoregod** [comment]
hello any news about this?

**Comment by synthsage** [comment]
Having the same issue.

**Comment by niunisas** [comment]
Hi.

@incoregod if you successfully spawn pets from config, then just set your keybinds in Settings -> Keybinds -> FiveM. There you should see two keybinds.

**Comment by incoregod** [comment]
Tnhks got it.

A quarta, 16/03/2022, 21:52, Niunisas ***@***.***> escreveu:
