### ISSUE TITLE
how does it even work 

### ISSUE THREAD

**Issue by lawtonalex** [FelisDevelopment/fd-pets-support#3]
supposedly im suppose to get an unnamed item to buy pets what is the item or where is the location??

**Comment by niunisas** [comment]
Did you read documentation? Did check QB, ESX adaptations?

**Comment by lawtonalex** [comment]
so theres no file in the resource that i can access its all obsufucated or whatever i looked over the documentation but that explains server events and such im very lost

**Comment by lawtonalex** [comment]
sorry for the late response i went out of town for a while
