### ISSUE TITLE
ACE Permission system

### ISSUE THREAD

**Issue by ezzkn** [FelisDevelopment/fd-pets-support#4]
I add ace permission to the command spawnpet in the .cfg file but it is saying "Access denied" We tried to have the item in the inventory and without any item in inventory. 
add_ace identifier.steam:xxxxxxx command.spawnpet allow
What ist wrong?

**Comment by niunisas** [comment]
Hi,
add_ace should be a group. So for example
```cfg
add_principal group.petspawning
add_ace group.petspawning command.spawnpet allow

add_principal identifier.steam:hex group.petspawning
```

**Comment by niunisas** [comment]
No answer. Closing.
